### ISSUE TITLE
Upload certificate to opencerts.io and the webpage display it as Invalid Certificate

### ISSUE THREAD

**Issue by erwinsg** [GovTechSG/opencerts-documentation#5]
I follow the steps provided in your documentation to deploy the certificate store, create and batching the certificate, issue the certificate, but when i upload the certificate to opencerts.io, the webpage display it as Invalid Certificate.

I have attached the screen capture for my testing for your reference.

Please advise. Thanks.
[Test_20180915.zip](https://github.com/GovTechSG/opencerts-documentation/files/2385115/Test_20180915.zip)

**Comment by yehjxraymond** [comment]
Hi, can you kindly attach your certificate file here? Thank you.

**Comment by yehjxraymond** [comment]
Hi,

Thank you for your report, we are currently doing an upgrade over this weekend. Your certificate file seemed to be correctly formatted. Once our next update is rolled out, it should be fixed. We will update you again!

**Comment by rjchow** [comment]
Your cert file's perfectly valid, just a bug with our system because we updated some versions and it hasn't been reflected on here. Hang in there we'll get it sorted coming week!

**Comment by erwinsg** [comment]
Please let me know again if I can resume my testing.
Thanks.

**Comment by yehjxraymond** [comment]
Hi, the viewer has been updated. You should now see that the certificate is verified with warning (because the certificate store address is not entered into the registry).
